CREATE GENERATOR BATTLE_MEMBERS_ID;
SET GENERATOR BATTLE_MEMBERS_ID TO 0;


CREATE TRIGGER BATTLE_MEMBERS_BI FOR BATTLE_MEMBERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.BATTLE_MEMBERS_ID IS NULL) THEN
NEW.BATTLE_MEMBERS_ID = GEN_ID(BATTLE_MEMBERS_ID,1);
END