CREATE OR ALTER SEQUENCE BATTLE_MEMBERS_ID START WITH 0 INCREMENT BY 1;

CREATE TRIGGER BATTLE_MEMBERS_BI FOR BATTLE_MEMBERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.BATTLE_MEMBERS_ID IS NULL) THEN
NEW.BATTLE_MEMBERS_ID = GEN_ID(BATTLE_MEMBERS_ID,1);
END