CREATE TABLE BATTLES (
    BATTLE_NAME VARCHAR(100) PRIMARY KEY,
    BATTLE_DATE DATE
);

INSERT INTO BATTLES (BATTLE_NAME, BATTLE_DATE)
VALUES ('Battle of Midway', '1942-06-04');

INSERT INTO BATTLES (BATTLE_NAME, BATTLE_DATE)
VALUES ('Battle of the Denmark Strait', '1941-05-24');