CREATE TABLE WARSHIPS (
    "NAME" VARCHAR(50) NOT NULL,
    CLASS VARCHAR(50),
    COMMISSION_DATE DATE,
    DECOMMISSION_DATE DATE,
    CONSTRAINT INTEG_11 CHECK (DECOMMISSION_DATE IS NULL OR DECOMMISSION_DATE > COMMISSION_DATE),
    CONSTRAINT PK_WARSHIPS PRIMARY KEY ("NAME"),
);

INSERT INTO WARSHIPS ("NAME", "CLASS", COMMISSION_DATE, DECOMMISSION_DATE)
VALUES ('USS Enterprise','aircraft carrier', '1938-05-12', '1947-02-17');

INSERT INTO WARSHIPS ("NAME", CLASS, COMMISSION_DATE, DECOMMISSION_DATE)
VALUES ('Bismarck', 'battleship', '1940-08-24', '1941-05-27');