CREATE TABLE BATTLE_MEMBERS (
    BATTLE_MEMBERS_ID INTEGER NOT NULL,
    BATTLE_NAME VARCHAR(100),
    SHIP_NAME VARCHAR(100),
    RESULT VARCHAR(50),
    CONSTRAINT INTEG_PRIMARYKEY PRIMARY KEY (BATTLE_MEMBERS_ID),
    CONSTRAINT INTEG_11FOREIGNKEY FOREIGN KEY (BATTLE_NAME) REFERENCES BATTLES (BATTLE_NAME) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT INTEG_12FOREIGNKEY FOREIGN KEY (SHIP_NAME) REFERENCES WARSHIPS ("NAME") ON UPDATE CASCADE ON DELETE CASCADE
);


INSERT INTO BATTLE_MEMBERS (BATTLE_MEMBERS_ID, BATTLE_NAME, SHIP_NAME, RESULT)
VALUES (0,'Battle of Midway', 'USS Enterprise', 'Survived');


INSERT INTO BATTLE_MEMBERS (BATTLE_MEMBERS_ID, BATTLE_NAME, SHIP_NAME, RESULT)
VALUES (1,'Battle of the Denmark Strait', 'Bismarck', 'Damaged');

